# Generated by Django 5.1.7 on 2025-03-21 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_userprofile_virtualbalance_userprofile_virtualbonds_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_asset_symbol', models.CharField(max_length=10)),
                ('virtual_quantity', models.IntegerField(default=0)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='VirtualTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_asset_symbol', models.CharField(max_length=10)),
                ('virtual_quantity', models.IntegerField()),
                ('virtual_transaction_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('virtual_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('virtual_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('virtual_created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userprofile')),
            ],
        ),
    ]
