# Generated by Django 5.1.7 on 2025-03-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualportfolio',
            name='virtual_asset_symbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='virtualtransaction',
            name='virtual_asset_symbol',
            field=models.CharField(max_length=100),
        ),
    ]
