# Generated by Django 5.1.7 on 2025-03-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_bonds_userprofile_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='virtualbalance',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtualbonds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtualboughtsum',
            field=models.DecimalField(decimal_places=2, default=10000.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtualinsurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='virtualstocks',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
