# Generated by Django 5.1.7 on 2025-03-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userprofile_virtualbalance_userprofile_virtualbonds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='virtualboughtsum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
