# Generated by Django 5.1.7 on 2025-03-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('insurance', 'Insurance'), ('sip', 'SIP')], max_length=10),
        ),
    ]
