# Generated by Django 5.1.7 on 2025-03-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='asset',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='asset',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='asset_symbol',
            field=models.CharField(default='IBM', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='asset_symbol',
            field=models.CharField(default='IBM', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
