# Generated by Django 5.1.7 on 2025-03-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_asset_asset_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('bond', 'Bond'), ('insurance', 'Insurance')], max_length=10),
        ),
    ]
