# Generated by Django 5.1.7 on 2025-03-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_remove_transaction_asset_remove_portfolio_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='asset_symbol',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='asset_symbol',
            field=models.CharField(max_length=100),
        ),
    ]
